name: update-data

on:
  schedule:
    # Weekdays ~9:45pm UTC (after US market close)
    - cron: '45 21 * * 1-5'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install yfinance pandas requests

      - name: Generate data
        env:
          FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
          BILLIONS_PER_POINT: ${{ vars.BILLIONS_PER_POINT }}
        run: |
          python scripts/update.py

      - name: Commit and push data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/*.json
          if ! git diff --cached --quiet; then
            git commit -m "chore(data): auto-update $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
            git push
          else
            echo "No changes to commit."
          fi
